<body class="modern">
	<main>
		<div class="popup-container modern">
			<p class="choice">
				<button  class="options switch-mode">
					<img class="switcher" src="img/switch-off.png" alt='Abandonner' />
				</button>
				<span  class="modern"> Design simple</span>
			</p>
			<p class="choice">
				<button class="options switch-level">
					<img src="img/trafficsmall.png" alt="Changement de classement" />
				</button><span  class="modern"> Changer le niveau</span>
			</p>
			<h1 class="modern">Classement niveau I</h1>
			<div class="leaderboard">Bienvenu sur le tableau des scores</div>
		</div>
		<div class="loading-bar"></div>
	</main>
</body>
